### ISSUE TITLE
Client hangs if dns server can't be reached

### ISSUE THREAD

**Issue by cdekok** [reactphp/http-client#10]
If the dns server is not available the script will hang forever, in this case it was blocked by firewall.

**Comment by clue** [comment]
Hi @Mech7, can you add a gist to reproduce the issue you're having? I'll look into tracing this down if this is related to the underlying DNS component or if this is actually a bug here.

**Comment by clue** [comment]
We are not aware of any issues here and I believe this may have been fixed in the meantime.

Closing this due to a lack of feedback, so I'll close this for now. If this problem persists, please report back and we can look into this again :+1:
