### ISSUE TITLE
Remote content on change

### ISSUE THREAD

**Issue by ostap-mykhaylyak** [reactphp/http-client#102]
Hi, i have an remote API and i need to update echo $chunk everytime remote content change.

I use this exmple.
https://github.com/reactphp/http-client/blob/master/examples/02-post-json.php

Anyone can help me? Thanks.

**Comment by clue** [comment]
I'm not sure I follow exactly what you're trying to achieve, so I'll try my best to answer as I understand what you're trying to do. If anything's unclear, a simple gist (even pseudo code) could help us understand the challenge you're facing :+1: 

HTTP is essentially request-response, which means that you have to send a new request every time you want a new (changed) response. You may want to look into ServerSentEvents or WebSocket or even custom upgraded protocols on top of HTTP.

I hope this helps :+1:

**Comment by ostap-mykhaylyak** [comment]
@clue i'm try to implement infinite loop every 5 seconds, but not work :(
