### ISSUE TITLE
Request every 5 seconds

### ISSUE THREAD

**Issue by ostap-mykhaylyak** [reactphp/http-client#103]
i'm try to implement request every 5 seconds, but not work :(

I use this exmple.
https://github.com/reactphp/http-client/blob/master/examples/02-post-json.php

Anyone can help me? Thanks.

**Comment by legionth** [comment]
Hello @ostap-mykhaylyak,

what exactly isn't working? Do you have a small code example what you are trying?

**Comment by ostap-mykhaylyak** [comment]
`
se React\HttpClient\Client;
use React\HttpClient\Response;

$loop = React\EventLoop\Factory::create();
$client = new Client($loop);

function make_request($client, $data){
    $request = $client->request('POST', '*******************/', array(
    'Content-Type' => 'application/json',
    'Content-Length' => strlen($data)
));

$request->on('response', function (Response $response) {
    // var_dump($response->getHeaders());
    $response->on('data', function ($chunk) {
            echo $chunk;
    });
});

$request->end($data);
}

$data = json_encode($my_some_data_array);
make_request($client, $data);

$loop->run();
`

Now if i make while loop ( while(1){} ) on make_request function, nothing happen.

**Comment by WyriHaximus** [comment]
```php
$loop->addPeriodicTimer(5, function () {
    $data = json_encode($my_some_data_array);
    make_request($client, $data);
});

$loop->run();
```

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
