### ISSUE TITLE
Unable to validate "1  " as chunk length header

### ISSUE THREAD

**Issue by DangerLifter** [reactphp/http-client#115]
I got stable exception "Unable to validate "1  " as chunk length header".
Test url "http://www.samaraphone.ru/530300.shtml".
Probably trim() could be solution;

**Comment by WyriHaximus** [comment]
Just tested it locally and could fetch that URL without issues. Which version are `react/http-client` are you using?

**Comment by clue** [comment]
Can you show a gist to reproduce the problem you're seeing? This should help us investigate further and maybe provide a solution for this.

Note that "1 " (with trailing whitespace) is invalid as per [RFC 7230](https://tools.ietf.org/html/rfc7230#section-4.1). Do you happen to have an idea what kind of software would produce this and how other HTTP clients (curl, browsers etc.) would handle this?
