### ISSUE TITLE
client pool

### ISSUE THREAD

**Issue by hustneverland** [reactphp/http-client#133]
if i have thousands of requests needed to send,how can i set a http client pool？

**Comment by clue** [comment]
Right now, this project does limit the number of concurrent connections (see also #129). As discussed in that ticket, you may want to give https://github.com/clue/reactphp-mq or https://github.com/clue/reactphp-flux a try if you want to handle a large number of concurrent requests.

I hope this helps :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
