### ISSUE TITLE
Support for certificate authentication when using HttpClientAdapter

### ISSUE THREAD

**Issue by TaelmanTim** [reactphp/http-client#140]
Is it possible to authenticate with certificate and private key when using this client and the HttpClientAdapter? Executing the following curl command is successful.
 ```
curl -i -v --request POST https://example.com --cert certificate.pem --key private_key.pem --cert-type pem --tlsv1.1
```

**Comment by clue** [comment]
If you need custom connector settings (DNS resolution, TLS parameters, timeouts, proxy servers etc.), you can explicitly pass a custom instance of the `ConnectorInterface` to the `Client` like this:

```php
$connector = new \React\Socket\Connector($loop, array(
    'tls' => array(
        'local_cert' => 'certificate.pem',
        'local_pk' => 'private_key.pem',
        'crypto_method' => STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT
    )
));

$client = new Client($loop, $connector);
```

I haven't verified the above options, but you can use this array to define any of PHP's context options: https://www.php.net/manual/en/context.ssl.php

I hope this helps :+1:
