### ISSUE TITLE
is $loop->run(); blocking?

### ISSUE THREAD

**Issue by erlangp** [reactphp/http-client#147]

**Comment by WyriHaximus** [comment]
It starts the loop. But to be honest I need more context to answer your question fully

**Comment by erlangp** [comment]
```php
// ...
echo 'A';
$loop->run();
echo 'B';
exit();
```

**Comment by WyriHaximus** [comment]
Right so as long as the loop has to do something it will keep running. And since `$loop->run();` is the method that kicks the loop it will block until it run out of things to do.

**Comment by erlangp** [comment]
owh thanks sir @WyriHaximus
