### ISSUE TITLE
Implement gzip content encoding

### ISSUE THREAD

**Issue by clue** [reactphp/http-client#37]

**Comment by WyriHaximus** [comment]
:+1: , fully agree on adding this. My main concern is how to do it non-blocking. A child process could be an option unless you know a good way to do it streaming chunk by chunk in future ticks.

**Comment by clue** [comment]
Gzip encoding/decoding should in fact not actually be part of this library. It should be added as a dependency here.

I suppose it makes sense to build this on top of [PHP's ZLib functions](http://php.net/manual/en/ref.zlib.php). I've started looking into building a streaming gzip encoder/decoder a while ago but have never been quite happy with its API.

Can't promise anything, but I'll try to look into this :+1:

**Comment by WyriHaximus** [comment]
It should not be part of this library at all but we need to find a way to make it non-blocking so we can use it within this library. A streaming encoder/decoder sounds great and that is something we could use in react/http as well.

**Comment by clue** [comment]
> make it non-blocking

IMO this is a non-issue for two reasons:

* zlib can easily decompress 100+ MByte/s on even a moderate system
* React PHP's Stream implementation uses usual chunk sizes of 4 KiB each

This means that using a blocking decompressing algorithm for individual chunks can be considered non-blocking for the purpose of this library :-)

(Obviously, this doesn't apply if you're decompressing a multi-megabyte string variable – which does not apply to this library)

**Comment by clue** [comment]
> Can't promise anything, but I'll try to look into this :+1:

Just for the reference, I've started looking into the available implementation approaches a few weeks ago: https://github.com/clue/php-zlib-react/issues/1

Using PHP's zlib stream filters works *okay-ish*. I'm currently working around some of its limitations:
https://github.com/clue/php-zlib-react/issues/3#issuecomment-153904756

**Comment by clue** [comment]
For the reference again, I've pushed an initial v0.1.0 release of [clue/zlib-react](https://github.com/clue/php-zlib-react) a few days ago. This can now be integrated here to offer HTTP compression support (`gzip` and/or `deflate`).

I hear @WyriHaximus is working on this? :+1:

**Comment by WyriHaximus** [comment]
Not just working, I have a working prototype getting molded into a PR :)

**Comment by CharlotteDunois** [comment]
@WyriHaximus What is the status of your prototype?

**Comment by WyriHaximus** [comment]
@CharlotteDunois about 3 and a half years old now so no clue. Feel free to build something because it has been ages

**Comment by clue** [comment]
I have to close this one as per #152 now that future development will focus on https://github.com/reactphp/http instead.

I've migrated this ticket to reactphp/http#377.
