### ISSUE TITLE
Implement chunked transfer encoding

### ISSUE THREAD

**Issue by clue** [reactphp/http-client#38]
Refs #5

**Comment by clue** [comment]
Receiving incoming responses with chunked transfer encoding has been resolved via #58.

We may still want to implement sending requests with chunked transfer encoding.

**Comment by CharlotteDunois** [comment]
@clue Since this package links now to the higher level implementation `buzz`, do we still want to implement sending chunked transfer encoding in this component? This would mean moving the logic from `buzz` to this component (which should probably be fairly straight forward).

**Comment by WyriHaximus** [comment]
@CharlotteDunois yes that's the goal

**Comment by clue** [comment]
What @WyriHaximus said :-)

The goal is to make https://github.com/clue/reactphp-buzz redundant in the future so that we can deprecate it and only rely on @ReactPHP's HTTP component :muscle:

**Comment by clue** [comment]
I'm closing this as it is already supported by the new HTTP client that has been merged into `react/http` via reactphp/http#368 :shipit: You should upgrade as per #152 :+1:
