### ISSUE TITLE
Implement following redirections

### ISSUE THREAD

**Issue by clue** [reactphp/http-client#40]

**Comment by WyriHaximus** [comment]
#20 is a PR providing this, given it has to be updated

**Comment by clue** [comment]
I'm not sure how reasonable this features is, given the current interface. The request represents a stream which will be sent to the original URI only and we should look into what could possibly be sent to the redirected target URI then.

We may want to block this until PSR-7 support is in via #41 first?

**Comment by clue** [comment]
I'm closing this as it is already supported by the new HTTP client that has been merged into `react/http` via reactphp/http#368 :shipit: You should upgrade as per #152 :+1:
