### ISSUE TITLE
Look into HTTP/2.0 support

### ISSUE THREAD

**Issue by clue** [reactphp/http-client#42]
Refs #5

**Comment by clue** [comment]
Currently, only HTTP/1.1 and HTTP/1.0 are supported, I'd love to see anybody picking up HTTP/2.0 support :+1: :tada:

**Comment by WyriHaximus** [comment]
@clue I'm looking into this though keep-alive support first because it's a stepping stone to HTTP/2.0

**Comment by clue** [comment]
I have to close this one as per #152 now that future development will focus on https://github.com/reactphp/http instead.

See also reactphp/http#99.
