### ISSUE TITLE
What about HTTP 1.1 support?

### ISSUE THREAD

**Issue by Sharom** [reactphp/http-client#5]

**Comment by WyriHaximus** [comment]
Yeah going to look into that and see if I can make some progress on that soon. It works fine in most cases but there are some edge cases where forcing it to `1.0` causes issues.

**Comment by deathmood** [comment]
Please tell me where I am wrong, `cause it does not work for me - I can not get response body with HTTP 1.1:

$request = $client->request('GET', 'http://facebook.com', [], '1.1');
$request->on('response', function ($res) {
    $res->on('data', function ($data, $res) {
        var_dump($data);
    });
});
it does not work for http://vk.com, http://facebook.com
why?

**Comment by WyriHaximus** [comment]
@deathmood answered your question here: https://github.com/reactphp/http-client/pull/49#issuecomment-149054443
