### ISSUE TITLE
Allow client creation without DNS resolver

### ISSUE THREAD

**Issue by andig** [reactphp/http-client#57]
According to https://github.com/reactphp/socket-client/blob/master/src/Connector.php#L9 Connector is deprecated. This could allow to change https://github.com/reactphp/http-client/blob/master/src/Factory.php#L12 by providing a default NULL resolver and in that case use a TcpConnector instead of a DnsConnector.

This would require upping socket-client dependency to 0.5 from 0.3 but would allow reducing some boilerplate code especially for simple test apps and local installations.

**Comment by clue** [comment]
Consider the `Factory` to be there for convenience only. If you do not need DNS resolution, you can also set up the `Client` yourself like this:

```php
$connector = new TcpConnector($loop);
$secureConnector = new SecureConnector($connector, $loop);

$client = new Client($connector, $secureConnector);
```

**Comment by andig** [comment]
Darn, so obvious. Thanks ;)
