### ISSUE TITLE
Response can sometimes emits data twice with incompatible arguments

### ISSUE THREAD

**Issue by mmelvin0** [reactphp/http-client#65]
I'm struggling to reproduce this and I can't anymore, but it's fairly clear in the code this is possible. There are two places where the `data` event for a `Response` can be triggered.

In [Response::handleData](https://github.com/reactphp/http-client/blob/f799ca6b31367da355aa3dbc1d7cd6b79d16ccba/src/Response.php#L80) the arguments are `string`, `Response`.

In [Request::handleData](https://github.com/reactphp/http-client/blob/123cd86d9ae0734ac29bb75c8e13a60ef2cf08a1/src/Request.php#L159) the arguments are `Psr\Http\Message\StreamInterface`, `Response`.

The latter seems to be correct, happens all the time, and what I want to incrementally read from the stream, so I just wrap my own `handleData` logic in `$stream instanceof StreamInterface` but that feels smelly.

The thing I can't reproduce is when `Response::handleData` gets called. It was happening to me every single time the responding server threw a fatal PHP error, now I can't make it happen. Also of interesting note it was returning only part of the PHP error text, although the stream itself yielded the entire text.

Also of note this is with v0.4.10 (I'll update to the latest) but the code is identical in your master branch.

**Comment by clue** [comment]
Thanks for spotting! :+1: The second occurrence should be cast to string so that it *always* emits a string data event. Does anybody feel like filing a trivial PR? :)

FWIW: The `StreamInterface` also has a `__toString()` method, so this can safely be used along with the expected strings. This is likely why this hasn't been noticed yet.

**Comment by WyriHaximus** [comment]
A PR would be every welcome 👍 . Fancy doing that @mmelvin0?

**Comment by mmelvin0** [comment]
The FWIW part of @clue's comment clarified everything for me. I should have been following the spirit of the examples rather than looking deeper into what was actually being passed to me. It also helped me realize that doing `instanceof StreamInterface` is broken as it will ignore subsequent response chunks.

@WyriHaximus I've made a pull request with a subtle modification to RequestTest that fails when `$bodyChunk` isn't cast to a string.

**Comment by clue** [comment]
Closed via #66

Thanks for looking into this, much appreciated! :+1:
