### ISSUE TITLE
Incomplete control code while parsing chunked stream

### ISSUE THREAD

**Issue by uniquoooo** [reactphp/http-client#67]
Hi,

I'm using `wyrihaximus/react-guzzle-psr7` to send async requests with Guzzle HTTP, however, the server I am requesting has recently started using chunked HTTP requests. I saw that chunked requests was recently introduced into the HTTP client by the creator of the package I am using however I am still getting the error `Stream ended with incomplete control code`. Is this a client side problem?

Thanks

**Comment by clue** [comment]
> Is this a client side problem?

We'll have to figure this out :-)

Have you checked the server is actually sending a valid chunked encoded stream? Can you post a public URL to test this?

The server might close the connection prematurely which would result in this error. Perhaps we *may* want to look into providing a non-strict parser (*Be strict in what you send, but generous in what you receive*).

**Comment by WyriHaximus** [comment]
Hey @uniquoooo the `Stream ended with incomplete control code` exception is thrown when the request ends in an unclean way. Do you have a easy way to reproduce this issue?

**Comment by uniquoooo** [comment]
Hi guys,

There isn't a public URL that I can post as it requires authorization, however, I can capture the response. Would it be fine if I capture it with `curl -iv --raw`?

Thanks

**Comment by clue** [comment]
Might be worth a try :+1: Otherwise a pcap (Wireshark etc.) may also help.

**Comment by uniquoooo** [comment]
I've uploaded it to GitHub gist here: https://gist.github.com/uniquoooo/c6c05261dbd67dd5f7c3ab5563927a14

**Comment by WyriHaximus** [comment]
@uniquoooo cheers, running tests with it ATM

**Comment by WyriHaximus** [comment]
@uniquoooo any change you can supply a pcap of the communication between your code and that server for a request that fails? Just put your gist into `DecodeChunkedStreamTest` as a data set, and it passed decoding the message.

If you don't want to share the pcap publicly (which I would discourage tbh) feel free to send it to the email address on my profile.

**Comment by uniquoooo** [comment]
@WyriHaximus I've done some more testing (which I should have done at the start) and I only get errors when I am using your `react-guzzle-psr7` wrapper. If I do the request through react/http-client it works fine. Should I create an issue over there?

**Comment by uniquoooo** [comment]
@WyriHaximus I've captured the request but I'm not sure how to export it, could you help?

**Comment by WyriHaximus** [comment]
@uniquoooo Wireshark has a `Save as` option that just saves the entire capure. I can open the pcapng (or just pcap) file on my machine and go through the request.

**Comment by uniquoooo** [comment]
@WyriHaximus I've sent you an email with the file.

**Comment by WyriHaximus** [comment]
Managed to reproduce the issue with  help from @uniquoooo, tracking down the cause of it and will submit a PR with a fix once I've came up with a solution.

**Comment by WyriHaximus** [comment]
So the chunked decoding parser is fine, the flaw turns out to be in the moment the headers are parsed and there is a bit of body coming with it from the stream. That bit of body was emitted from the response object while it should have been emitted from the stream. #68 is up to fix that.

**Comment by WyriHaximus** [comment]
[`v0.4.14`](https://github.com/reactphp/http-client/releases/tag/v0.4.14) has been tagged fixing this issue, thanks again for reporting :+1:

**Comment by uniquoooo** [comment]
Thanks for your help @WyriHaximus!

**Comment by brad-jones** [comment]
@WyriHaximus Not sure if it's related to this issue or not.

In `ChunkedTreamDecoder->handleEnd()`, the value of `$this->buffer` looks like this:

```
string(5) "0

"
```

If I comment out the check of `$this->buffer` then my request works fine.

How would you suggest the easiest way to get you a packet dump, considering this is over TLS.
ie: A Normal pcap dump will be encrypted uselessness to you.

**Comment by brad-jones** [comment]
Here are 3 files, captured each time fread was hit before the `Stream ended with incomplete control code` exception is thrown.

I have removed / swapped out the sensitive stuff (most of which is just the body of a SOAP request).

[react-http-client-issue.1478816829.3675.txt](https://github.com/reactphp/http-client/files/584954/react-http-client-issue.1478816829.3675.txt)
[react-http-client-issue.1478816829.3692.txt](https://github.com/reactphp/http-client/files/584952/react-http-client-issue.1478816829.3692.txt)
[react-http-client-issue.1478816829.3693.txt](https://github.com/reactphp/http-client/files/584953/react-http-client-issue.1478816829.3693.txt)

**Comment by WyriHaximus** [comment]
@brad-jones thanks, currently debugging :+1:

**Comment by WyriHaximus** [comment]
@brad-jones could you verify for me that the hot fix I just created works for you? You can test that by swapping `vendor/src/react/http-client/src/ChunkedStreamDecoder.php` out with this one [`ChunkedStreamDecoder.php`](https://gist.github.com/WyriHaximus/203237c41c811fcf8d528f092f73efe5) in the mean time I'll write up tests as well for it and create a PR.

**Comment by Akhawais** [comment]
Using [WyriHaximus/react-guzzle-psr7](/WyriHaximus/react-guzzle-psr7):

Async works as expected. However synchronous responses almost always fail.

Sending a sync to Stream Labs API (Which uses chunked transfer encoding) fails with `Connection closed before receiving response`.

@WyriHaximus Your hotfix has successfuly fixed the issue for me. Thanks for all your continued support!

**Comment by Akhawais** [comment]
It's now causing some requests to hang the whole React loop indefinitely. Not sure if it's the hotfix.

**Comment by WyriHaximus** [comment]
> It's now causing some requests to hang the whole React loop indefinitely. Not sure if it's the hotfix.

It isn't, the hotfix applied to a specific situation where there is some data left to process. It should never let the loop run indefinitely on it's own.

**Comment by Akhawais** [comment]
Thanks for clearing that up! Posted an [issue](/WyriHaximus/react-guzzle-psr7/issues/18) in your handler repo but pretty sure it belongs here if it uses `http-client`.

**Comment by WyriHaximus** [comment]
No problem, locally trying to figure out what exactly went wrong. In my cause I was hitting the Blizzard API which sometimes causes the error

**Comment by WyriHaximus** [comment]
@brad-jones @Akhawais If you have time could you test this hotfix with me? https://gist.github.com/WyriHaximus/b6891672a4aaa78830076004b2c7839a It seems to be running fine on my end right now but would appreciate your help testing it

**Comment by brad-jones** [comment]
Yeah its been on my todo list. Ill try and get to it today.

**Comment by WyriHaximus** [comment]
Awesome, let me know how it performs for you :+1:

**Comment by Akhawais** [comment]
@WyriHaximus Seems to work fine. Can do more tests when I'm home and will report back.

**Comment by WyriHaximus** [comment]
@Akhawais awesome, glad to hear that, I'll get the PR up tonight.
