### ISSUE TITLE
Merge into Http component and deprecate HttpClient component

### ISSUE THREAD

**Issue by clue** [reactphp/http-client#78]
Opening this for the reference and to raise awareness. Note that there's an ongoing discussion as to whether this component should be merged into the Http component.

See https://github.com/reactphp/http/issues/148 for details.

**Comment by andig** [comment]
I'm currently looking into this and am a bit stumped on how to convert a Psr `StreamInterface` into a react `ReadableStream`. Any ideas? Either this is not an "easy pick" or just beyond my skills :/

**Comment by clue** [comment]
@andig It sounds like this might be related to #41 instead of this ticket? It's my understanding that #41 has priority first and once that's addressed, merging the two components should be an easy pick :shipit:

**Comment by andig** [comment]
@clue thank you. I didn't realize there was already work going on. Better letting you guys do your magic :)

**Comment by mdrost** [comment]
Is it possible that when this components will be merged into react/http then this repository could become something like react version of GuzzleHttp with all Psr7 goodies (better version of clue/php-react-buzz)?

**Comment by WyriHaximus** [comment]
Define

> all Psr7 goodies

and 

> better version of clue/php-react-buzz

cause not sure what exactly you're looking for :wink:

**Comment by clue** [comment]
Superseded and closed via https://github.com/reactphp/http/pull/368 / #152  :shipit:
