### ISSUE TITLE
Utilities/documentation for testing of client's code.

### ISSUE THREAD

**Issue by Sharom** [reactphp/http-client#9]

**Comment by clue** [comment]
Hi @Sharom, I'm not sure I follow, what exactly are you asking for? :-)

Admittedly, both the documentation and the tests aren't *quite perfect*, but IMO both should help you getting started? PRs welcome, I guess? :-)

**Comment by clue** [comment]
The documentation and tests have been updated in the meantime and we now also have some examples (#69).

I hope this helps :+1: 

I believe this has been answered, so I'll close this for now. If this problem persists, please report back and we can look into this again :+1:
