### ISSUE TITLE
Support for Expect: 100 continue

### ISSUE THREAD

**Issue by nick4fake** [reactphp/http-client#94]
Now when we support Transfer-Encoding: chunked it would be great to have at least basic continue support. I'll file example MR soon

**Comment by clue** [comment]
Yes, please :+1: 

Self-quoting from our server-side implementation: https://github.com/reactphp/http/issues/109#issuecomment-278958298

> Thanks for filing this ticket and sparking the discussion about our expect-continue feature (`Expect: 100-continue`) :+1: 
>
> First things first, here's how this works in the first place:
>
> * This feature is specified as part of HTTP/1.1: https://tools.ietf.org/html/rfc7231#section-5.1.1
>* Clients MAY implement this feature but are not required to do so
>* Severs MAY implement this feature but are not required to do so
>* If the client includes a `Expect: 100-continue` header, the server MAY return an intermediary `HTTP/1.1 100 Continue` response after receiving the request headers, which causes the client to start transmitting the actual message body
>* If the client includes a `Expect: 100-continue` header, the server MAY reject the request with any "normal" error response message, which means the client never has to transmit the message body at all
>* Clients MUST support servers that do not implement this feature. This usually adds a few seconds of delay where the client waits for the intermediary `HTTP/1.1 100 Continue` response
>* Many common clients actually implement this feature when sending *large* requests only (usually a few KiB or MiB)

This means that it makes sense to automatically use this for certain requests, but we should probably provide an option to turn this off.

**Comment by clue** [comment]
Again thanks for bringing this up! I have to close this one as per #152 now that future development will focus on https://github.com/reactphp/http instead.

I've migrated the feature request to reactphp/http#378.
