### ISSUE TITLE
Add docs for request error handling

### ISSUE THREAD

**Issue by Fneufneu** [reactphp/http-client#96]
Examples miss a really important point: error handly for a request like a simple timeout.
simply like this:
```PHP
$request = $client->request('GET', $url);
$request->on('error', function ($e) {
  $socketerror = $e->getPrevious();
  echo "request failed with error: " . $e->getMessage() . PHP_EOL;
});
```
I spend too much time just for this so i think it should be added in the README or the exemple section.

**Comment by WyriHaximus** [comment]
@Fneufneu sounds reasonable, could you create a PR adding documentation for this?

**Comment by WyriHaximus** [comment]
@Fneufneu So @clue already fixed it though: https://github.com/reactphp/http-client/pull/97
